In [1]:
%load_ext autoreload
%autoreload 2

In [17]:
import pandas as pd
import os, sys
import numpy as np

In [19]:
new_x = pd.read_csv('../data/samples_2.csv')
spectra = pd.read_excel('../data/spectra_2.xlsx', index_col=0, engine='openpyxl')  
for i,(_,Ii) in enumerate(spectra.items()):
    np.savetxt('../data/%d_uvvis.txt'%i, Ii, delimiter=',')
    break

In [8]:
new_x

    PEG10k-stock  PEG5k-stock  octanethiol-stock  water-stock
0           61.0         37.0               45.0         57.0
1           19.0         89.0               41.0         51.0
2           53.0         50.0               58.0         39.0
3           74.0         27.0                9.0         91.0
4           72.0         36.0               15.0         77.0
5           94.0         67.0               35.0          4.0
6           59.0         41.0               43.0         57.0
7           89.0         13.0               46.0         52.0
8           32.0         65.0               29.0         74.0
9           61.0         39.0               18.0         82.0
10          85.0         31.0                6.0         77.0
11          75.0         68.0                9.0         48.0
12          83.0         58.0               39.0         20.0
13          22.0        133.0               44.0          0.0
14          17.0         82.0               41.0         60.0